env:
  browser: true
  es6: true
  node: true
  commonjs: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - off
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  no-console: 0
  no-unused-vars: warn